name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest   

    steps:
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/checkout@v4
    - name: Use latest Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - run: npm ci
    - run: npm i -g karma
    - run: npm i -g cat
    - run: npm i rxjs
    - run: npm run test:all
